# Generated by Django 5.0.3 on 2024-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(to="todo.tag"),
        ),
    ]
